'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<<<<<<< HEAD
Partial Public Class Index5
=======
'Partial Public Class Index5

Partial Public Class IndexMaquina

>>>>>>> c5d508946dbceacf78a075aeb1afaf8e841b2b6f
End Class
